Develop
JavierClairvaux/px-usewithcare pull request #3
Opened 2020-06-09 20:48 UTC by JavierClairvaux

2020-06-11 02:10 UTC, zasgar requested changes
I gave feedback on cpuburn.go. Will look at memeater a bit later.

2020-06-11 02:10 UTC, zasgar commented on cpuburner/cpuburner.go
> +import (
A few high level notes. The code won't currently pass our style check. Here are some suggestions:

1. Public methods should be commented. In go style starting with the function name. 
2. init functions should be the first function in the file. 
3. Although this is unlikely you are unsafely accessing state across multiple handler.

2020-06-11 02:10 UTC, zasgar commented on cpuburner/cpuburner.go
> +
These don't need to be global variables.

2020-06-11 02:10 UTC, zasgar commented on cpuburner/cpuburner.go
> +}
It looks like we create a new burner for every start, but kill them all on the stop. We should either treat start/stop the same. Which means: 

1. We can have start/stop work on only a single burner. 
2. If we want to support multiple burners we should return an ID (I think this is excessive and not needed).

2020-06-11 02:10 UTC, zasgar commented on cpuburner/cpuburner.go
> +}
The get end point above is also inconsistent.

2020-06-11 02:10 UTC, zasgar commented on cpuburner/cpuburner.go
> +
I don't think we should take flags at all for this. 

I think a better API will be: 

PUT /cpuburn/count.  <-  # of CPUs
GET /cpuburn/count.  <-  returns # of CPUs
Delete /cpuburn.  <-  stops it. Equivalent of PUT /cpuburn/count --> 0

2020-06-15 01:13 UTC, zasgar requested changes

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +
Isn't this already running a goroutine? No need to add another level of goroutine with the select {} that will just cause this goroutine to leak.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +
Does not need to be public right?

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +		cpuBurner: map[string]*CPUBurner{},
make(map[string]*CPUBurner)

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +}
It's not super likely but this should be either sync.Map or a protected by mutex.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +
This is more like a stopped jobs monitor since it will always run in the background.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +	id, found := mux.Vars(r)["id"]
can you just use r.Query()? 

Also, res is typically named "w" in Go.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +	UpdateInterval int    `json:"ttl"`
This is actually TimeToLive right?

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +		io.WriteString(res, "{'error': 'id not found'}")
We should add an error struct that you can serialize with JSON.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +			http.Error(res, err.Error(), http.StatusInternalServerError)
usually not a good idea to write the error message to an external API. This a toy program so I guess it's probably ok,but as a matter of style it's better to write something like "Failed to serialize the output".

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +}
Stylistically, it's better to handle the errors first. This leads to less nested code.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +		http.Error(res, err.Error(), http.StatusInternalServerError)
see note about errors above.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +	"github.com/rs/xid"
can we use: https://github.com/satori/go.uuid 

We use that for most of code base.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +	ID             string `json:"id,omitempty"`
Why not store the UUID type if that is what we are going to use? I actually think in this case it'll be more friendly to just use an incrementing ID.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +}
See note about style above.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +
We should have a GET handler to get a list of IDs.

2020-06-15 01:13 UTC, zasgar commented on cpuburner/cpuburner.go
> +	NumBurn        int    `json:"num_burn"`
To simplify the interface a bit, I think you should remove the NumBurn here. We can add a Post endpoint where you just pass in N to create a number of CPU burners.

2020-06-15 01:13 UTC, zasgar commented on memeater/memeater.go
> +import (
I think we can basically share most of the code with CPU burner if you abstract the resource burner part into an interface. That way we can easily add other resource burners.

2020-06-15 01:13 UTC, zasgar commented on memeater/memeater.go
> +//char* cEater(int s);
I am trying to understand why this requires CGO. Can you clarify?

2020-06-15 17:00 UTC, zasgar requested changes

2020-06-15 17:00 UTC, zasgar commented on cpuburner/cpuburner.go
> +}
I am trying to understand why this is needed at all. Can't the loop above just check if it's over the TTL and die?

2020-06-15 20:34 UTC, JavierClairvaux commented on cpuburner/cpuburner.go
> +	id, found := mux.Vars(r)["id"]
I think I'm going to keep using  mux, it is easier to write restful urls and more consistent with less code, as for your second suggestion I already made that change

2020-06-16 21:09 UTC, JavierClairvaux commented on memeater/memeater.go
> +import (
For now I think we are going to put this on the trello dashboard and get back to it when we have time

2020-06-17 22:52 UTC, zasgar commented on cpuburner/cpuburner.go
> +	fmt.Printf("Sleeping %d miliseconds\n", c.TTL)
The conical go way of doing this is to use a channel. There is an unlikely issue concurrency issue that might cause bad behavior here.

2020-06-17 22:52 UTC, zasgar commented on cpuburner/cpuburner.go
> +		time.Sleep(1 * time.Second)
why do you need the sleep here?

2020-06-17 22:52 UTC, zasgar commented on cpuburner/cpuburner.go
> +				c.mutex.Lock()
I think you need to hold the mutex when iterating.

2020-06-17 22:52 UTC, zasgar commented on cpuburner/cpuburner.go
> +	}
usually not a great idea to fatal error. It's probably better to return an internal error.

2020-06-17 22:52 UTC, zasgar commented on memeater/memeater.go
> +import (
The code on both of these paths basically looks the exact same. So we should probably refactor it.

2020-06-19 15:12 UTC, thetonymaster commented on cpuburner/cpuburner.go
> +	fmt.Printf("Sleeping %d miliseconds\n", c.TTL)
There is no need to synchronize this goroutines since they will just die when the countdown ends.

2020-06-19 15:51 UTC, zasgar commented on cpuburner/cpuburner.go
> +	fmt.Printf("Sleeping %d miliseconds\n", c.TTL)
The problem isn't synchronizing the goroutine. It's has to do with the c.Running. Normally programs when they do this is to use a quitCh and close it. It's not good form to just set c.Running = False.

2020-06-19 18:49 UTC, thetonymaster commented on cpuburner/cpuburner.go
> +}
`c.Running` is checked by the monitor, if it's false it will be removed from the list

2020-06-19 18:51 UTC, thetonymaster commented on cpuburner/cpuburner.go
> +		time.Sleep(1 * time.Second)
It will also eat a couple of CPU's if this is left without sleep, in the new version it is always eating a couple of CPU's more, will try to change this to goroutines instead, to see if this goes away
![image](https://user-images.githubusercontent.com/5334244/85171044-e5668980-b233-11ea-8f63-afd6dc9ec12e.png)

2020-08-14 17:45 UTC, merged